server:
  port: 4000
  servlet:
    context-path: /api/v1

app:
  name: broketopia-backend
  version: 0.0.1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/broketopia
    username: broketopia
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false